### ISSUE TITLE
How to convert image to .bin

### ISSUE THREAD

**Issue by Yohannfra** [embeddedt/lv_img_conv#1]
Hello, I'm trying to use this script to convert a bunch of png files to .bin but can't find the flag to do so.

Thanks

**Comment by embeddedt** [comment]
Currently this converter can only output C files, not `.bin` files. However, I do plan to add support for the other format eventually.

Related: https://github.com/lvgl/lv_utils/issues/38#issuecomment-916258582

**Comment by Yohannfra** [comment]
Ok thanks for your answer. Since I need to convert many images to .bin format I made a script that uses the old php image converter to help me do so. 

You can find it here if you or anyone in the future needs it https://github.com/Yohannfra/lvgl_batch_image_converter

Thanks

**Comment by embeddedt** [comment]
A very untested version of this is now implemented. See https://github.com/lvgl/lv_utils/issues/38#issuecomment-922145968.
